[editor]
scrolloff = 5
mouse = true
default-yank-register = '"'
middle-click-paste = true
scroll-lines = 3
cursorline = false
cursorcolumn = false
continue-comments = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
auto-completion = true
path-completion = true
auto-format = true

[editor.cursor-shape]
normal = "underline"
insert = "underline"
select = "underline"
